#!/usr/bin/env ruby

require 'iodine'

# Iodine::Rack.app = proc { [200, { 'X-Sendfile' => File.expand_path("#{File.dirname(__FILE__) }/index.html") }, []] }
Iodine::Rack.app = proc { [404, { 'X-Sendfile' => File.expand_path("#{File.dirname(__FILE__) }/index.html") }, []] }
Iodine::Rack.public = File.dirname(__FILE__)

Iodine.threads = 8
Iodine.start
